site_name: drone_awe


theme:
# pip install mkdocs-material
    name: 'material'
    palette:
        primary: 'blue grey'
        accent: 'grey'
    font:
        text: 'Roboto Slab'
        code: 'Source Code Pro'
    logo:
        icon: 'home'
        
    # feature:
        # tabs: true
        
    extra:
      social:
        - type: 'github'
          link: 'https://github.com/flythereddflagg'
        # - type: 'twitter'
          # link: 'https://twitter.com/squidfunk'
        # - type: 'linkedin'
          # link: 'https://linkedin.com/in/squidfunk'
